### ISSUE TITLE
Example doesen't work

### ISSUE THREAD

**Issue by nov1n** [h2non/baloo#13]
The following example doesn't work for me. In particular the expected json is null. Also httpbin now uses nginx instead of apache.

```
package simple

import (
  "testing"

  "gopkg.in/h2non/baloo.v1"
)

// test stores the HTTP testing client preconfigured
var test = baloo.New("http://httpbin.org")

func TestBalooSimple(t *testing.T) {
  test.Get("/get").
    SetHeader("Foo", "Bar").
    Expect(t).
    Status(200).
    Header("Server", "apache").
    Type("json").
    JSON(map[string]string{"bar": "foo"}).
    Done()
}
```

**Comment by marcel** [comment]
The issue is this line: [https://github.com/h2non/baloo/blob/master/assert/json.go#L65

If you pass in `map[string]string{"foo":"bar"}` when it gets to `data.(map[string]interface{})` it returns `nil, false` rather than `map[string]string{"foo":"bar"}, true`. You could work around it by passing `map[string]interface{}{"foo":"bar"}` but using the more direct typing in the example is obviously preferable.

**Comment by h2non** [comment]
This is fixed.
